from enum import Enum

class CURRENTSTATUS(Enum):
    READING=1
    RECORDING=2
    ERROR=3
    MISSING=4
    UNDEFINED=5

class PASTSTATUS(Enum):
    ALLCLEAR=1
    PASTERROR=2
    
class REPORTEDERRORSTATUS(Enum):
    CURRENT=1
    PAST=2
    NEVER=3

class PROCESSEDPACKETRESULT(Enum):
    WRONGID=1
    CHECKSUMERROR=2
    WRONGNUMBYTES=3
    NOANSWER=4
    OKAY=5

class INSTRUCTIONSETTYPE(Enum):
    LINEAR=1,
    REPEATING=2,
    CIRCADIAN=3,
    CONSTANT=4

class DARKSTATE(Enum):
    OFF=1,
    ON=2,
    UNCONTROLLED=3

class OPTOLIDTYPE(Enum):
    NONE=1
    ONECHAMBER=2,
    SIXCHAMBER=3,
    TWELVECHAMBER=4

class MESSAGETYPE(Enum):
    NOTICE=1,
    WARNING=2,
    ERROR=3

class OPTOTYPE(Enum):
    ALLON=1,
    ADAPTIVE=2